window.indicators = [
    { name: 'Accumulation Distribution', value: 'ACCD@tv-basicstudies' },
    { name: 'Advance Decline Ratio Bars', value: 'studyADR@tv-basicstudies' },
    { name: 'Anchored VWAP', value: 'AnchoredVWAP@tv-basicstudies' },
    { name: 'Aroon', value: 'AROON@tv-basicstudies' },
    { name: 'Average True Range', value: 'ATR@tv-basicstudies' },
    { name: 'Awesome Oscillator', value: 'AwesomeOscillator@tv-basicstudies' },
    { name: 'Bollinger Bands', value: 'BB@tv-basicstudies' },
    { name: 'Bollinger Bands B', value: 'BollingerBandsR@tv-basicstudies' },
    { name: 'Bollinger Bands Width', value: 'BollingerBandsWidth@tv-basicstudies' },
    { name: 'CCI', value: 'CCI@tv-basicstudies' },
    { name: 'Chaikin Money Flow', value: 'CMF@tv-basicstudies' },
    { name: 'Chaikin Oscillator', value: 'ChaikinOscillator@tv-basicstudies' },
    { name: 'Chande Momentum Oscillator', value: 'chandeMO@tv-basicstudies' },
    { name: 'Choppiness Index', value: 'ChoppinessIndex@tv-basicstudies' },
    { name: 'Connors RSI', value: 'CRSI@tv-basicstudies' },
    { name: 'DEMA', value: 'DoubleEMA@tv-basicstudies' },
    { name: 'DMI', value: 'DM@tv-basicstudies' },
    { name: 'Donchian Channels', value: 'DONCH@tv-basicstudies' },
    { name: 'DPO', value: 'DetrendedPriceOscillator@tv-basicstudies' },
    { name: 'Ease Of Movement', value: 'EaseOfMovement@tv-basicstudies' },
    { name: 'EMA', value: 'MAExp@tv-basicstudies' },
    { name: 'ENV', value: 'ENV@tv-basicstudies' },
    { name: 'EFI', value: 'EFI@tv-basicstudies' },
    { name: 'Fisher Transform', value: 'FisherTransform@tv-basicstudies' },
    { name: 'Historical Volatility', value: 'HV@tv-basicstudies' },
    { name: 'Hull MA', value: 'hullMA@tv-basicstudies' },
    { name: 'Ichimoku Cloud', value: 'IchimokuCloud@tv-basicstudies' },
    { name: 'Keltner Channels', value: 'KLTNR@tv-basicstudies' },
    { name: 'MACD', value: 'MACD@tv-basicstudies' },
    { name: 'Momentum', value: 'MOM@tv-basicstudies' },
    { name: 'Money Flow', value: 'MF@tv-basicstudies' },
    { name: 'OBV', value: 'On_Balance_Volume@tv-basicstudies' },
    { name: 'PSAR', value: 'PSAR@tv-basicstudies' },
    { name: 'Price Oscillator', value: 'PriceOsc@tv-basicstudies' },
    { name: 'Price Oscillator', value: 'PriceOsc@tv-basicstudies' },
    { name: 'Price Volume Trend', value: 'PriceVolumeTrend@tv-basicstudies' },
    { name: 'Pivot Points HighLow', value: 'PivotPointsHighLow@tv-basicstudies' },
    { name: 'Pivot Points Standard', value: 'PivotPointsStandard@tv-basicstudies' },
    { name: 'Relative Vigor Index', value: 'VigorIndex@tv-basicstudies' },
    { name: 'Relative Volatility Index', value: 'VolatilityIndex@tv-basicstudies' },
    { name: 'ROC', value: 'ROC@tv-basicstudies' },
    { name: 'RSI', value: 'RSI@tv-basicstudies' },
    { name: 'SMI Ergodic Indicator Oscillator', value: 'SMIErgodicIndicator@tv-basicstudies' },
    { name: 'SMI Ergodic Oscillator', value: 'SMIErgodicOscillator@tv-basicstudies' },
    { name: 'SMA', value: 'MASimple@tv-basicstudies' },
    { name: 'Stochastic', value: 'Stochastic@tv-basicstudies' },
    { name: 'Stochastic RSI', value: 'StochasticRSI@tv-basicstudies' },
    { name: 'TEMA', value: 'TripleEMA@tv-basicstudies' },
    { name: 'TRIX', value: 'Trix@tv-basicstudies' },
    { name: 'Ultimate Oscillator', value: 'UltimateOsc@tv-basicstudies' },
    { name: 'VWMA', value: 'MAVolumeWeighted@tv-basicstudies' },
    { name: 'Williams Alligator', value: 'WilliamsAlligator@tv-basicstudies' },
    { name: 'Williams Fractals', value: 'WilliamsFractal@tv-basicstudies' },
    { name: 'Williams R', value: 'WilliamR@tv-basicstudies' },
    { name: 'WMA', value: 'MAWeighted@tv-basicstudies' }
];

